### ISSUE TITLE
License not specified

### ISSUE THREAD

**Issue by divi255** [aQaTL/htpasswd-verify#5]
Good day

could you please specify the library license?

**Comment by aQaTL** [comment]
Hello

The license is set to `Apache-2.0` in the `Cargo.toml` file: https://github.com/aQaTL/htpasswd-verify/blob/476e5171e8a9b843003f2985f70ef676d6ee90c3/Cargo.toml#L6

Is that not enough?

**Comment by divi255** [comment]
thank you!
